### ISSUE TITLE
Error: InvalidModel(InvalidModelError { msg: "unsupported character type: 4" })

### ISSUE THREAD

**Issue by lovelock** [daac-tools/vaporetto#110]
I need Chinese model and found some in http://www.phontron.com/kytea/download/model/as-0.4.0-1.mod.gz , all the models found in this site can't be converted.

macOS 13.4.1 with M1 chip

```
cargo run --release -p convert_kytea_model -- --model-in as-0.4.0-1.mod --model
-out as-0.4.0-1.mod.zst
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/convert_kytea_model --model-in as-0.4.0-1.mod --model-out as-0.4.0-1.mod.zst`
Loading model file...
Saving model file...
Error: InvalidModel(InvalidModelError { msg: "unsupported character type: 4" })
```

**Comment by vbkaisetsu** [comment]
@lovelock Thank you for reporting this issue.

I have checked that model and it seems to be broken.
KyTea maps the Unicode characters in the training data to IDs, and the map contained in the model is read by the following function:
https://github.com/neubig/kytea/blob/73a94c4a3045087a7e90f27700f3b870a72625e7/src/lib/string-util.cpp#L223C1-L223C1
The character map contains both surface characters and character type identifiers (`R`, `K`, `O`, ...).

In `as-0.4.0-1.mod`, the 6203-th character of the list is `\u{4}` and some character type features refer it. However, such a character type is invalid according to the source code:
https://github.com/neubig/kytea/blob/73a94c4a3045087a7e90f27700f3b870a72625e7/src/lib/string-util.cpp#L58

KyTea does not check identifiers so features containing invalid character types are simply not used, but Vaporetto checks that, so the error occurs.

**Comment by vbkaisetsu** [comment]
@lovelock I do not want to support buggy models at this time. However, you can still use that model by applying the following patch and ignoring the invalid character type identifier.

At here:
https://github.com/daac-tools/vaporetto/blob/dbbe79461614293c62956a1ccbd24603b05bd119/vaporetto/src/kytea_model.rs#L482-L508

Patches:
* Line 482:
   ```diff
   -        for (type_ngram, v) in type_dict.dump_items() {
   +        'a: for (type_ngram, v) in type_dict.dump_items() {
   ```
* Line 498-500
   ```diff
   -                        return Err(VaporettoError::invalid_model(format!(
   -                            "unsupported character type: {t}"
   -                        )));
   +                        continue 'a;
   ```
