### ISSUE TITLE
add verb dictionary tag

### ISSUE THREAD

**Issue by UESTC-LXY** [daac-tools/vaporetto#131]
Can you add the Japanese base form, also known as the dictionary form?"

**Comment by vbkaisetsu** [comment]
@UESTC-LXY Sorry for the late reply.

The following model contains lemmas. Could you try this?
https://github.com/daac-tools/vaporetto/releases/download/v0.5.0/bccwj-suw+unidic+tag-lemma.tar.xz

```
cargo run --release -p predict -- --model '/home/k-akabe/Downloads/bccwj-suw+unidic+tag-lemma/bccwj-suw+unidic+tag-lemma.model.zst' --predict-tags
風が吹いている
風/名詞-普通名詞-一般/カゼ/風 が/助詞-格助詞/ガ/が 吹い/動詞-一般/フイ/吹く て/助詞-接続助詞/テ/て いる/動詞-非自立可能/イル/居る
```

`吹い` → `吹く`
