### ISSUE TITLE
Cannot deserialize predictor

### ISSUE THREAD

**Issue by rabbit19981023** [daac-tools/vaporetto#86]
I want to serialize & deserialize predictor to persistent it in file to reduce model building time when used as cli tool.

But I got `DecodeError(UnexpectedEnd { additional: 1 })` error when deserializing.

However, when changing the parameter of `predict_tags` to `false`, deserializing works, but I need the yomi of each token.

Is it a bug or I missed something?

Here's my code:
```rust
use std::fs::File;
use std::io::Read;
use vaporetto::{Model, Predictor};

fn main() {
    let file = File::open("./model.zst").unwrap();
    let mut decoder = ruzstd::StreamingDecoder::new(file).unwrap();
    let mut buffer = vec![];
    decoder.read_to_end(&mut buffer).unwrap();
    let (model, _) = Model::read_slice(&buffer).unwrap();

    // when predict_tags set to false, it works
    let predictor = Predictor::new(model, true).unwrap();

    let serialized = predictor.serialize_to_vec().unwrap();
    unsafe { Predictor::deserialize_from_slice_unchecked(&serialized).unwrap(); }
    // DecodeError(UnexpectedEnd { additional: 1 })
}
```

**Comment by vbkaisetsu** [comment]
@rabbit19981023 I fixed a bug.
Could you confirm the behavior again?

**Comment by rabbit19981023** [comment]
@vbkaisetsu

Yes, serializing & deserializing all goes well now. Thanks for fast bug fixing!

And I have another question not related to this case:

I could use `ruzstd::StreamingDecoder` to create Model instance like what the wasm example source code does. But how to just use `std::fs::File::open` or `std::fs::read` to do the same stuff?

Example use `model.bin`, and the downloaded one use `.zst` extension, how could I convert `.zst` extension to `.bin`?

```rust
// these codes works fine
let model_data = read("./model.zst").unwrap();
let mut decoder = ruzstd::StreamingDecoder::new(model_data.as_slice()).unwrap();
let mut buffer = vec![];
decoder.read_to_end(&mut buffer).unwrap();
let (model, _) = Model::read_slice(&buffer).unwrap();

// these codes panic
let file = File::open("./model.zst").unwrap();
let model = Model::read(file).unwrap();
// Error: "model version mismatch"
```

**Comment by vbkaisetsu** [comment]
@rabbit19981023 I created a pull request to explain the zstd format. (#88)

We don't have any plan to support the zstd format in the vapretto API, but you can also decompress these files yourself using the unzstd command, which is contained in modern Linux distributions.

For further discussion, please reply at #88, not here.

**Comment by rabbit19981023** [comment]
Thank you for the detail description !
